package Clases;

import java.awt.Frame;
import java.awt.Window;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        llenar();
        //<html>ANALIZAR<br /><br />JUGADA</html> 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_color = new javax.swing.ButtonGroup();
        bg_jugada = new javax.swing.ButtonGroup();
        jd_movimientos = new javax.swing.JDialog();
        lb_A3 = new javax.swing.JLabel();
        lb_A4 = new javax.swing.JLabel();
        lb_B1 = new javax.swing.JLabel();
        lb_A6 = new javax.swing.JLabel();
        lb_A8 = new javax.swing.JLabel();
        lb_A5 = new javax.swing.JLabel();
        lb_A1 = new javax.swing.JLabel();
        lb_A7 = new javax.swing.JLabel();
        lb_C4 = new javax.swing.JLabel();
        lb_C3 = new javax.swing.JLabel();
        lb_C5 = new javax.swing.JLabel();
        lb_C8 = new javax.swing.JLabel();
        lb_C6 = new javax.swing.JLabel();
        lb_C2 = new javax.swing.JLabel();
        lb_C7 = new javax.swing.JLabel();
        lb_C1 = new javax.swing.JLabel();
        lb_E4 = new javax.swing.JLabel();
        lb_E3 = new javax.swing.JLabel();
        lb_E5 = new javax.swing.JLabel();
        lb_E8 = new javax.swing.JLabel();
        lb_E6 = new javax.swing.JLabel();
        lb_E2 = new javax.swing.JLabel();
        lb_E7 = new javax.swing.JLabel();
        lb_E1 = new javax.swing.JLabel();
        lb_G4 = new javax.swing.JLabel();
        lb_G3 = new javax.swing.JLabel();
        lb_G5 = new javax.swing.JLabel();
        lb_G8 = new javax.swing.JLabel();
        lb_G6 = new javax.swing.JLabel();
        lb_G2 = new javax.swing.JLabel();
        lb_G7 = new javax.swing.JLabel();
        lb_G1 = new javax.swing.JLabel();
        lb_A2 = new javax.swing.JLabel();
        lb_B7 = new javax.swing.JLabel();
        lb_B5 = new javax.swing.JLabel();
        lb_B3 = new javax.swing.JLabel();
        lb_B2 = new javax.swing.JLabel();
        lb_B6 = new javax.swing.JLabel();
        lb_B4 = new javax.swing.JLabel();
        lb_B8 = new javax.swing.JLabel();
        lb_D7 = new javax.swing.JLabel();
        lb_D5 = new javax.swing.JLabel();
        lb_D6 = new javax.swing.JLabel();
        lb_D3 = new javax.swing.JLabel();
        lb_D2 = new javax.swing.JLabel();
        lb_D8 = new javax.swing.JLabel();
        lb_D4 = new javax.swing.JLabel();
        lb_D1 = new javax.swing.JLabel();
        lb_F5 = new javax.swing.JLabel();
        lb_F7 = new javax.swing.JLabel();
        lb_F1 = new javax.swing.JLabel();
        lb_F4 = new javax.swing.JLabel();
        lb_F3 = new javax.swing.JLabel();
        lb_F6 = new javax.swing.JLabel();
        lb_F8 = new javax.swing.JLabel();
        lb_F2 = new javax.swing.JLabel();
        lb_H5 = new javax.swing.JLabel();
        lb_H7 = new javax.swing.JLabel();
        lb_H1 = new javax.swing.JLabel();
        lb_H4 = new javax.swing.JLabel();
        lb_H3 = new javax.swing.JLabel();
        lb_H6 = new javax.swing.JLabel();
        lb_H8 = new javax.swing.JLabel();
        lb_H2 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jb_nuevaPartida = new javax.swing.JButton();
        jLabel81 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<String>();
        rb_negro = new javax.swing.JRadioButton();
        rb_blanco = new javax.swing.JRadioButton();
        jb_ingresarCoordenadas = new javax.swing.JButton();
        tf_posicion = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb_caballo = new javax.swing.JRadioButton();
        rb_peon = new javax.swing.JRadioButton();
        rb_rey = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jd_movimientosLayout = new javax.swing.GroupLayout(jd_movimientos.getContentPane());
        jd_movimientos.getContentPane().setLayout(jd_movimientosLayout);
        jd_movimientosLayout.setHorizontalGroup(
            jd_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_movimientosLayout.setVerticalGroup(
            jd_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        lb_A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_A4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 75, 75));

        lb_B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_B1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 75, 75));

        lb_A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_A6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 75, 75));

        lb_A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_A8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 75, 75));

        lb_A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        lb_A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        lb_A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        lb_C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_C4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 75, 75));

        lb_C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        lb_C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        lb_C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_C8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 75, 75));

        lb_C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_C6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 75, 75));

        lb_C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_C2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 75, 75));

        lb_C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        lb_C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        lb_E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_E4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 75, 75));

        lb_E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        lb_E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, -1, -1));

        lb_E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_E8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 75, 75));

        lb_E6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_E6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 75, 75));

        lb_E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_E2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 75, 75));

        lb_E7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, -1, -1));

        lb_E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        lb_G4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_G4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 690, 75, 75));

        lb_G3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 690, -1, -1));

        lb_G5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 690, -1, -1));

        lb_G8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_G8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 690, 75, 75));

        lb_G6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_G6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, 75, 75));

        lb_G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_G2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 690, 75, 75));

        lb_G7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 690, -1, -1));

        lb_G1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 690, -1, -1));

        lb_A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_A2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 75, 75));

        lb_B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_B7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 75, 75));

        lb_B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_B5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 75, 75));

        lb_B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_B3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 75, 75));

        lb_B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        lb_B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        lb_B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        lb_B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        lb_D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_D7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 75, 75));

        lb_D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_D5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 75, 75));

        lb_D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        lb_D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_D3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 75, 75));

        lb_D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        lb_D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        lb_D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        lb_D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 75, 75));

        lb_F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_F5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 75, 75));

        lb_F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_F7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 75, 75));

        lb_F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_F1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 75, 75));

        lb_F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, -1, -1));

        lb_F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_F3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 75, 75));

        lb_F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, -1, -1));

        lb_F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, -1, -1));

        lb_F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, -1, -1));

        lb_H5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_H5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 770, 75, 75));

        lb_H7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_H7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 770, 75, 75));

        lb_H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_H1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 770, 75, 75));

        lb_H4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 770, -1, -1));

        lb_H3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white_tile.png"))); // NOI18N
        lb_H3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb_H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 770, 75, 75));

        lb_H6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 770, -1, -1));

        lb_H8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 770, -1, -1));

        lb_H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gray_tile.png"))); // NOI18N
        getContentPane().add(lb_H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 770, -1, -1));

        jLabel65.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(51, 51, 51));
        jLabel65.setText("A");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 25, 26));

        jLabel66.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(51, 51, 51));
        jLabel66.setText("D");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 25, 26));

        jLabel67.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(51, 51, 51));
        jLabel67.setText("B");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 25, 26));

        jLabel68.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(51, 51, 51));
        jLabel68.setText("C");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 25, 26));

        jLabel69.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(51, 51, 51));
        jLabel69.setText("F");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 25, 26));

        jLabel70.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(51, 51, 51));
        jLabel70.setText("G");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 25, 26));

        jLabel71.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(51, 51, 51));
        jLabel71.setText("H");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 790, 25, 26));

        jLabel72.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(51, 51, 51));
        jLabel72.setText("E");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 25, 26));

        jLabel73.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(51, 51, 51));
        jLabel73.setText("1");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 25, 26));

        jLabel74.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(51, 51, 51));
        jLabel74.setText("2");
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 25, 26));

        jLabel75.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(51, 51, 51));
        jLabel75.setText("3");
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 25, 26));

        jLabel76.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(51, 51, 51));
        jLabel76.setText("4");
        getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 25, 26));

        jLabel77.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(51, 51, 51));
        jLabel77.setText("5");
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 25, 26));

        jLabel78.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(51, 51, 51));
        jLabel78.setText("6");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 25, 26));

        jLabel79.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(51, 51, 51));
        jLabel79.setText("7");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 25, 26));

        jLabel80.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(51, 51, 51));
        jLabel80.setText("8");
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 25, 26));

        jPanel1.setBackground(new java.awt.Color(67, 67, 67));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));

        jb_nuevaPartida.setBackground(new java.awt.Color(102, 102, 102));
        jb_nuevaPartida.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jb_nuevaPartida.setForeground(new java.awt.Color(102, 0, 102));
        jb_nuevaPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/new.png"))); // NOI18N
        jb_nuevaPartida.setText("NUEVA PARTIDA");
        jb_nuevaPartida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_nuevaPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevaPartidaMouseClicked(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("SELECCIONE LA PIEZA");

        cb_tipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CABALLO", "REY", "PEON" }));

        bg_color.add(rb_negro);
        rb_negro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb_negro.setForeground(new java.awt.Color(255, 255, 255));
        rb_negro.setText("NEGRO");

        bg_color.add(rb_blanco);
        rb_blanco.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb_blanco.setForeground(new java.awt.Color(255, 255, 255));
        rb_blanco.setSelected(true);
        rb_blanco.setText("BLANCO");

        jb_ingresarCoordenadas.setBackground(new java.awt.Color(102, 102, 102));
        jb_ingresarCoordenadas.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jb_ingresarCoordenadas.setForeground(new java.awt.Color(102, 0, 102));
        jb_ingresarCoordenadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        jb_ingresarCoordenadas.setText("INGRESAR PIEZA");
        jb_ingresarCoordenadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarCoordenadasMouseClicked(evt);
            }
        });

        tf_posicion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel82.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("POSICIÓN DE LA PIEZA");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(227, 227, 227));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/89-64.png"))); // NOI18N
        jButton1.setText("<html> A N A L I Z A R <br />J U G A D A</html> ");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        bg_jugada.add(rb_caballo);
        rb_caballo.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        rb_caballo.setForeground(new java.awt.Color(255, 255, 255));
        rb_caballo.setText("COMER UN CABALLO");

        bg_jugada.add(rb_peon);
        rb_peon.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        rb_peon.setForeground(new java.awt.Color(255, 255, 255));
        rb_peon.setText("CORONAR UN PEÓN");

        bg_jugada.add(rb_rey);
        rb_rey.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        rb_rey.setForeground(new java.awt.Color(255, 255, 255));
        rb_rey.setText("JAQUE AL REY");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/decorative-swirl-with-shadow-hi.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_rey)
                    .addComponent(rb_peon)
                    .addComponent(rb_caballo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rb_negro)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rb_blanco)
                                        .addComponent(jLabel81))
                                    .addGap(3, 3, 3))
                                .addComponent(jLabel82))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_nuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_ingresarCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jb_nuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel81)
                .addGap(18, 18, 18)
                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_blanco)
                    .addComponent(rb_negro))
                .addGap(18, 18, 18)
                .addComponent(jLabel82)
                .addGap(18, 18, 18)
                .addComponent(tf_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_ingresarCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_caballo)
                        .addGap(18, 18, 18)
                        .addComponent(rb_peon)
                        .addGap(18, 18, 18)
                        .addComponent(rb_rey))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 430, 660));

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 90)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("C H E S S  O R A C L E");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 950, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/decorative-swirl-with-shadow-hi.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 870, 310, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/decorative-swirl-with-shadow-hi.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 350, 60));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/white-wallpaper-18 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1300, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ingresarCoordenadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarCoordenadasMouseClicked
        // TODO add your handling code here:
        Icon whorse_wt = new ImageIcon("src/Icons/whorse_wt.png");
        Icon wpawn_wt = new ImageIcon("src/Icons/wpawn_wt.png");
        Icon wking_wt = new ImageIcon("src/Icons/wking_wt.png");
        Icon bhorse_wt = new ImageIcon("src/Icons/bhorse_wt.png");
        Icon bpawn_wt = new ImageIcon("src/Icons/bpawn_wt.png");
        Icon bking_wt = new ImageIcon("src/Icons/bking_wt.png");
        Icon whorse_bt = new ImageIcon("src/Icons/whorse_bt.png");
        Icon wpawn_bt = new ImageIcon("src/Icons/wpawn_bt.png");
        Icon wking_bt = new ImageIcon("src/Icons/wking_bt.png");
        Icon bhorse_bt = new ImageIcon("src/Icons/bhorse_bt.png");
        Icon bpawn_bt = new ImageIcon("src/Icons/bpawn_bt.png");
        Icon bking_bt = new ImageIcon("src/Icons/bking_bt.png");
        String posicion = tf_posicion.getText();
        String tipo = cb_tipo.getSelectedItem().toString();
        char fila = posicion.charAt(0);
        char columna = posicion.charAt(1);
        switch (tipo) {
            case "CABALLO":
                if (rb_blanco.isSelected()) {//caballos blancos
                    if (fila == 'A') {
                        if (columna == '1') {
                            lb_A1.setIcon(whorse_bt);
                        } else if (columna == '2') {
                            lb_A2.setIcon(whorse_wt);
                        } else if (columna == '3') {
                            lb_A3.setIcon(whorse_bt);
                        } else if (columna == '4') {
                            lb_A4.setIcon(whorse_wt);
                        } else if (columna == '5') {
                            lb_A5.setIcon(whorse_bt);
                        } else if (columna == '6') {
                            lb_A6.setIcon(whorse_wt);
                        } else if (columna == '7') {
                            lb_A7.setIcon(whorse_bt);
                        } else if (columna == '8') {
                            lb_A8.setIcon(whorse_wt);
                        }
                    }
                    if (fila == 'B') {
                        if (columna == '1') {
                            lb_B1.setIcon(whorse_wt);
                        } else if (columna == '2') {
                            lb_B2.setIcon(whorse_bt);
                        } else if (columna == '3') {
                            lb_B3.setIcon(whorse_wt);
                        } else if (columna == '4') {
                            lb_B4.setIcon(whorse_bt);
                        } else if (columna == '5') {
                            lb_B5.setIcon(whorse_wt);
                        } else if (columna == '6') {
                            lb_B6.setIcon(whorse_bt);
                        } else if (columna == '7') {
                            lb_B7.setIcon(whorse_wt);
                        } else if (columna == '8') {
                            lb_B8.setIcon(whorse_bt);
                        }
                    }
                    if (fila == 'C') {
                        if (columna == '1') {
                            lb_C1.setIcon(whorse_bt);
                        } else if (columna == '2') {
                            lb_C2.setIcon(whorse_wt);
                        } else if (columna == '3') {
                            lb_C3.setIcon(whorse_bt);
                        } else if (columna == '4') {
                            lb_C4.setIcon(whorse_wt);
                        } else if (columna == '5') {
                            lb_C5.setIcon(whorse_bt);
                        } else if (columna == '6') {
                            lb_C6.setIcon(whorse_wt);
                        } else if (columna == '7') {
                            lb_C7.setIcon(whorse_bt);
                        } else if (columna == '8') {
                            lb_C8.setIcon(whorse_wt);
                        }
                    }
                    if (fila == 'D') {
                        if (columna == '1') {
                            lb_D1.setIcon(whorse_wt);
                        } else if (columna == '2') {
                            lb_D2.setIcon(whorse_bt);
                        } else if (columna == '3') {
                            lb_D3.setIcon(whorse_wt);
                        } else if (columna == '4') {
                            lb_D4.setIcon(whorse_bt);
                        } else if (columna == '5') {
                            lb_D5.setIcon(whorse_wt);
                        } else if (columna == '6') {
                            lb_D6.setIcon(whorse_bt);
                        } else if (columna == '7') {
                            lb_D7.setIcon(whorse_wt);
                        } else if (columna == '8') {
                            lb_D8.setIcon(whorse_bt);
                        }
                    }
                    if (fila == 'E') {
                        if (columna == '1') {
                            lb_E1.setIcon(whorse_bt);
                        } else if (columna == '2') {
                            lb_E2.setIcon(whorse_wt);
                        } else if (columna == '3') {
                            lb_E3.setIcon(whorse_bt);
                        } else if (columna == '4') {
                            lb_E4.setIcon(whorse_wt);
                        } else if (columna == '5') {
                            lb_E5.setIcon(whorse_bt);
                        } else if (columna == '6') {
                            lb_E6.setIcon(whorse_wt);
                        } else if (columna == '7') {
                            lb_E7.setIcon(whorse_bt);
                        } else if (columna == '8') {
                            lb_E8.setIcon(whorse_wt);
                        }
                    }
                    if (fila == 'F') {
                        if (columna == '1') {
                            lb_F1.setIcon(whorse_wt);
                        } else if (columna == '2') {
                            lb_F2.setIcon(whorse_bt);
                        } else if (columna == '3') {
                            lb_F3.setIcon(whorse_wt);
                        } else if (columna == '4') {
                            lb_F4.setIcon(whorse_bt);
                        } else if (columna == '5') {
                            lb_F5.setIcon(whorse_wt);
                        } else if (columna == '6') {
                            lb_F6.setIcon(whorse_bt);
                        } else if (columna == '7') {
                            lb_F7.setIcon(whorse_wt);
                        } else if (columna == '8') {
                            lb_F8.setIcon(whorse_bt);
                        }
                    }
                    if (fila == 'G') {
                        if (columna == '1') {
                            lb_G1.setIcon(whorse_bt);
                        } else if (columna == '2') {
                            lb_G2.setIcon(whorse_wt);
                        } else if (columna == '3') {
                            lb_G3.setIcon(whorse_bt);
                        } else if (columna == '4') {
                            lb_G4.setIcon(whorse_wt);
                        } else if (columna == '5') {
                            lb_G5.setIcon(whorse_bt);
                        } else if (columna == '6') {
                            lb_G6.setIcon(whorse_wt);
                        } else if (columna == '7') {
                            lb_G7.setIcon(whorse_bt);
                        } else if (columna == '8') {
                            lb_G8.setIcon(whorse_wt);
                        }
                    }
                    if (fila == 'H') {
                        if (columna == '1') {
                            lb_H1.setIcon(whorse_wt);
                        } else if (columna == '2') {
                            lb_H2.setIcon(whorse_bt);
                        } else if (columna == '3') {
                            lb_H3.setIcon(whorse_wt);
                        } else if (columna == '4') {
                            lb_H4.setIcon(whorse_bt);
                        } else if (columna == '5') {
                            lb_H5.setIcon(whorse_wt);
                        } else if (columna == '6') {
                            lb_H6.setIcon(whorse_bt);
                        } else if (columna == '7') {
                            lb_H7.setIcon(whorse_wt);
                        } else if (columna == '8') {
                            lb_H8.setIcon(whorse_bt);
                        }
                    }
                } else {//caballos negros
                    if (fila == 'A') {
                        if (columna == '1') {
                            lb_A1.setIcon(bhorse_bt);
                        } else if (columna == '2') {
                            lb_A2.setIcon(bhorse_wt);
                        } else if (columna == '3') {
                            lb_A3.setIcon(bhorse_bt);
                        } else if (columna == '4') {
                            lb_A4.setIcon(bhorse_wt);
                        } else if (columna == '5') {
                            lb_A5.setIcon(bhorse_bt);
                        } else if (columna == '6') {
                            lb_A6.setIcon(bhorse_wt);
                        } else if (columna == '7') {
                            lb_A7.setIcon(bhorse_bt);
                        } else if (columna == '8') {
                            lb_A8.setIcon(bhorse_wt);
                        }
                    }
                    if (fila == 'B') {
                        if (columna == '1') {
                            lb_B1.setIcon(bhorse_wt);
                        } else if (columna == '2') {
                            lb_B2.setIcon(bhorse_bt);
                        } else if (columna == '3') {
                            lb_B3.setIcon(bhorse_wt);
                        } else if (columna == '4') {
                            lb_B4.setIcon(bhorse_bt);
                        } else if (columna == '5') {
                            lb_B5.setIcon(bhorse_wt);
                        } else if (columna == '6') {
                            lb_B6.setIcon(bhorse_bt);
                        } else if (columna == '7') {
                            lb_B7.setIcon(bhorse_wt);
                        } else if (columna == '8') {
                            lb_B8.setIcon(bhorse_bt);
                        }
                    }
                    if (fila == 'C') {
                        if (columna == '1') {
                            lb_C1.setIcon(bhorse_bt);
                        } else if (columna == '2') {
                            lb_C2.setIcon(bhorse_wt);
                        } else if (columna == '3') {
                            lb_C3.setIcon(bhorse_bt);
                        } else if (columna == '4') {
                            lb_C4.setIcon(bhorse_wt);
                        } else if (columna == '5') {
                            lb_C5.setIcon(bhorse_bt);
                        } else if (columna == '6') {
                            lb_C6.setIcon(bhorse_wt);
                        } else if (columna == '7') {
                            lb_C7.setIcon(bhorse_bt);
                        } else if (columna == '8') {
                            lb_C8.setIcon(bhorse_wt);
                        }
                    }
                    if (fila == 'D') {
                        if (columna == '1') {
                            lb_D1.setIcon(bhorse_wt);
                        } else if (columna == '2') {
                            lb_D2.setIcon(bhorse_bt);
                        } else if (columna == '3') {
                            lb_D3.setIcon(bhorse_wt);
                        } else if (columna == '4') {
                            lb_D4.setIcon(bhorse_bt);
                        } else if (columna == '5') {
                            lb_D5.setIcon(bhorse_wt);
                        } else if (columna == '6') {
                            lb_D6.setIcon(bhorse_bt);
                        } else if (columna == '7') {
                            lb_D7.setIcon(bhorse_wt);
                        } else if (columna == '8') {
                            lb_D8.setIcon(bhorse_bt);
                        }
                    }
                    if (fila == 'E') {
                        if (columna == '1') {
                            lb_E1.setIcon(bhorse_bt);
                        } else if (columna == '2') {
                            lb_E2.setIcon(bhorse_wt);
                        } else if (columna == '3') {
                            lb_E3.setIcon(bhorse_bt);
                        } else if (columna == '4') {
                            lb_E4.setIcon(bhorse_wt);
                        } else if (columna == '5') {
                            lb_E5.setIcon(bhorse_bt);
                        } else if (columna == '6') {
                            lb_E6.setIcon(bhorse_wt);
                        } else if (columna == '7') {
                            lb_E7.setIcon(bhorse_bt);
                        } else if (columna == '8') {
                            lb_E8.setIcon(bhorse_wt);
                        }
                    }
                    if (fila == 'F') {
                        if (columna == '1') {
                            lb_F1.setIcon(bhorse_wt);
                        } else if (columna == '2') {
                            lb_F2.setIcon(bhorse_bt);
                        } else if (columna == '3') {
                            lb_F3.setIcon(bhorse_wt);
                        } else if (columna == '4') {
                            lb_F4.setIcon(bhorse_bt);
                        } else if (columna == '5') {
                            lb_F5.setIcon(bhorse_wt);
                        } else if (columna == '6') {
                            lb_F6.setIcon(bhorse_bt);
                        } else if (columna == '7') {
                            lb_F7.setIcon(bhorse_wt);
                        } else if (columna == '8') {
                            lb_F8.setIcon(bhorse_bt);
                        }
                    }
                    if (fila == 'G') {
                        if (columna == '1') {
                            lb_G1.setIcon(bhorse_bt);
                        } else if (columna == '2') {
                            lb_G2.setIcon(bhorse_wt);
                        } else if (columna == '3') {
                            lb_G3.setIcon(bhorse_bt);
                        } else if (columna == '4') {
                            lb_G4.setIcon(bhorse_wt);
                        } else if (columna == '5') {
                            lb_G5.setIcon(bhorse_bt);
                        } else if (columna == '6') {
                            lb_G6.setIcon(bhorse_wt);
                        } else if (columna == '7') {
                            lb_G7.setIcon(bhorse_bt);
                        } else if (columna == '8') {
                            lb_G8.setIcon(bhorse_wt);
                        }
                    }
                    if (fila == 'H') {
                        if (columna == '1') {
                            lb_H1.setIcon(bhorse_wt);
                        } else if (columna == '2') {
                            lb_H2.setIcon(bhorse_bt);
                        } else if (columna == '3') {
                            lb_H3.setIcon(bhorse_wt);
                        } else if (columna == '4') {
                            lb_H4.setIcon(bhorse_bt);
                        } else if (columna == '5') {
                            lb_H5.setIcon(bhorse_wt);
                        } else if (columna == '6') {
                            lb_H6.setIcon(bhorse_bt);
                        } else if (columna == '7') {
                            lb_H7.setIcon(bhorse_wt);
                        } else if (columna == '8') {
                            lb_H8.setIcon(bhorse_bt);
                        }
                    }
                }
                break;
            case "PEON":
                if (rb_blanco.isSelected()) {//peones blancos
                    if (fila == 'A') {
                        if (columna == '1') {
                            lb_A1.setIcon(wpawn_bt);
                        } else if (columna == '2') {
                            lb_A2.setIcon(wpawn_wt);
                        } else if (columna == '3') {
                            lb_A3.setIcon(wpawn_bt);
                        } else if (columna == '4') {
                            lb_A4.setIcon(wpawn_wt);
                        } else if (columna == '5') {
                            lb_A5.setIcon(wpawn_bt);
                        } else if (columna == '6') {
                            lb_A6.setIcon(wpawn_wt);
                        } else if (columna == '7') {
                            lb_A7.setIcon(wpawn_bt);
                        } else if (columna == '8') {
                            lb_A8.setIcon(wpawn_wt);
                        }
                    }
                    if (fila == 'B') {
                        if (columna == '1') {
                            lb_B1.setIcon(wpawn_wt);
                        } else if (columna == '2') {
                            lb_B2.setIcon(wpawn_bt);
                        } else if (columna == '3') {
                            lb_B3.setIcon(wpawn_wt);
                        } else if (columna == '4') {
                            lb_B4.setIcon(wpawn_bt);
                        } else if (columna == '5') {
                            lb_B5.setIcon(wpawn_wt);
                        } else if (columna == '6') {
                            lb_B6.setIcon(wpawn_bt);
                        } else if (columna == '7') {
                            lb_B7.setIcon(wpawn_wt);
                        } else if (columna == '8') {
                            lb_B8.setIcon(wpawn_bt);
                        }
                    }
                    if (fila == 'C') {
                        if (columna == '1') {
                            lb_C1.setIcon(wpawn_bt);
                        } else if (columna == '2') {
                            lb_C2.setIcon(wpawn_wt);
                        } else if (columna == '3') {
                            lb_C3.setIcon(wpawn_bt);
                        } else if (columna == '4') {
                            lb_C4.setIcon(wpawn_wt);
                        } else if (columna == '5') {
                            lb_C5.setIcon(wpawn_bt);
                        } else if (columna == '6') {
                            lb_C6.setIcon(wpawn_wt);
                        } else if (columna == '7') {
                            lb_C7.setIcon(wpawn_bt);
                        } else if (columna == '8') {
                            lb_C8.setIcon(wpawn_wt);
                        }
                    }
                    if (fila == 'D') {
                        if (columna == '1') {
                            lb_D1.setIcon(wpawn_wt);
                        } else if (columna == '2') {
                            lb_D2.setIcon(wpawn_bt);
                        } else if (columna == '3') {
                            lb_D3.setIcon(wpawn_wt);
                        } else if (columna == '4') {
                            lb_D4.setIcon(wpawn_bt);
                        } else if (columna == '5') {
                            lb_D5.setIcon(wpawn_wt);
                        } else if (columna == '6') {
                            lb_D6.setIcon(wpawn_bt);
                        } else if (columna == '7') {
                            lb_D7.setIcon(wpawn_wt);
                        } else if (columna == '8') {
                            lb_D8.setIcon(wpawn_bt);
                        }
                    }
                    if (fila == 'E') {
                        if (columna == '1') {
                            lb_E1.setIcon(wpawn_bt);
                        } else if (columna == '2') {
                            lb_E2.setIcon(wpawn_wt);
                        } else if (columna == '3') {
                            lb_E3.setIcon(wpawn_bt);
                        } else if (columna == '4') {
                            lb_E4.setIcon(wpawn_wt);
                        } else if (columna == '5') {
                            lb_E5.setIcon(wpawn_bt);
                        } else if (columna == '6') {
                            lb_E6.setIcon(wpawn_wt);
                        } else if (columna == '7') {
                            lb_E7.setIcon(wpawn_bt);
                        } else if (columna == '8') {
                            lb_E8.setIcon(wpawn_wt);
                        }
                    }
                    if (fila == 'F') {
                        if (columna == '1') {
                            lb_F1.setIcon(wpawn_wt);
                        } else if (columna == '2') {
                            lb_F2.setIcon(wpawn_bt);
                        } else if (columna == '3') {
                            lb_F3.setIcon(wpawn_wt);
                        } else if (columna == '4') {
                            lb_F4.setIcon(wpawn_bt);
                        } else if (columna == '5') {
                            lb_F5.setIcon(wpawn_wt);
                        } else if (columna == '6') {
                            lb_F6.setIcon(wpawn_bt);
                        } else if (columna == '7') {
                            lb_F7.setIcon(wpawn_wt);
                        } else if (columna == '8') {
                            lb_F8.setIcon(wpawn_bt);
                        }
                    }
                    if (fila == 'G') {
                        if (columna == '1') {
                            lb_G1.setIcon(wpawn_bt);
                        } else if (columna == '2') {
                            lb_G2.setIcon(wpawn_wt);
                        } else if (columna == '3') {
                            lb_G3.setIcon(wpawn_bt);
                        } else if (columna == '4') {
                            lb_G4.setIcon(wpawn_wt);;
                        } else if (columna == '5') {
                            lb_G5.setIcon(wpawn_bt);
                        } else if (columna == '6') {
                            lb_G6.setIcon(wpawn_wt);
                        } else if (columna == '7') {
                            lb_G7.setIcon(wpawn_bt);
                        } else if (columna == '8') {
                            lb_G8.setIcon(wpawn_wt);
                        }
                    }
                    if (fila == 'H') {
                        if (columna == '1') {
                            lb_H1.setIcon(wpawn_wt);
                        } else if (columna == '2') {
                            lb_H2.setIcon(wpawn_bt);
                        } else if (columna == '3') {
                            lb_H3.setIcon(wpawn_wt);
                        } else if (columna == '4') {
                            lb_H4.setIcon(wpawn_bt);
                        } else if (columna == '5') {
                            lb_H5.setIcon(wpawn_wt);
                        } else if (columna == '6') {
                            lb_H6.setIcon(wpawn_bt);
                        } else if (columna == '7') {
                            lb_H7.setIcon(wpawn_wt);
                        } else if (columna == '8') {
                            lb_H8.setIcon(wpawn_bt);
                        }
                    }
                } else {//peones negros
                    if (fila == 'A') {
                        if (columna == '1') {
                            lb_A1.setIcon(bpawn_bt);
                        } else if (columna == '2') {
                            lb_A2.setIcon(bpawn_wt);
                        } else if (columna == '3') {
                            lb_A3.setIcon(bpawn_bt);
                        } else if (columna == '4') {
                            lb_A4.setIcon(bpawn_wt);
                        } else if (columna == '5') {
                            lb_A5.setIcon(bpawn_bt);
                        } else if (columna == '6') {
                            lb_A6.setIcon(bpawn_wt);
                        } else if (columna == '7') {
                            lb_A7.setIcon(bpawn_bt);
                        } else if (columna == '8') {
                            lb_A8.setIcon(bpawn_wt);
                        }
                    }
                    if (fila == 'B') {
                        if (columna == '1') {
                            lb_B1.setIcon(bpawn_wt);
                        } else if (columna == '2') {
                            lb_B2.setIcon(bpawn_bt);
                        } else if (columna == '3') {
                            lb_B3.setIcon(bpawn_wt);
                        } else if (columna == '4') {
                            lb_B4.setIcon(bpawn_bt);
                        } else if (columna == '5') {
                            lb_B5.setIcon(bpawn_wt);
                        } else if (columna == '6') {
                            lb_B6.setIcon(bpawn_bt);
                        } else if (columna == '7') {
                            lb_B7.setIcon(bpawn_wt);
                        } else if (columna == '8') {
                            lb_B8.setIcon(bpawn_bt);
                        }
                    }
                    if (fila == 'C') {
                        if (columna == '1') {
                            lb_C1.setIcon(bpawn_bt);
                        } else if (columna == '2') {
                            lb_C2.setIcon(bpawn_wt);
                        } else if (columna == '3') {
                            lb_C3.setIcon(bpawn_bt);
                        } else if (columna == '4') {
                            lb_C4.setIcon(bpawn_wt);
                        } else if (columna == '5') {
                            lb_C5.setIcon(bpawn_bt);
                        } else if (columna == '6') {
                            lb_C6.setIcon(bpawn_wt);
                        } else if (columna == '7') {
                            lb_C7.setIcon(bpawn_bt);
                        } else if (columna == '8') {
                            lb_C8.setIcon(bpawn_wt);
                        }
                    }
                    if (fila == 'D') {
                        if (columna == '1') {
                            lb_D1.setIcon(bpawn_wt);
                        } else if (columna == '2') {
                            lb_D2.setIcon(bpawn_bt);
                        } else if (columna == '3') {
                            lb_D3.setIcon(bpawn_wt);
                        } else if (columna == '4') {
                            lb_D4.setIcon(bpawn_bt);
                        } else if (columna == '5') {
                            lb_D5.setIcon(bpawn_wt);
                        } else if (columna == '6') {
                            lb_D6.setIcon(bpawn_bt);
                        } else if (columna == '7') {
                            lb_D7.setIcon(bpawn_wt);
                        } else if (columna == '8') {
                            lb_D8.setIcon(bpawn_bt);
                        }
                    }
                    if (fila == 'E') {
                        if (columna == '1') {
                            lb_E1.setIcon(bpawn_bt);
                        } else if (columna == '2') {
                            lb_E2.setIcon(bpawn_wt);
                        } else if (columna == '3') {
                            lb_E3.setIcon(bpawn_bt);
                        } else if (columna == '4') {
                            lb_E4.setIcon(bpawn_wt);
                        } else if (columna == '5') {
                            lb_E5.setIcon(bpawn_bt);
                        } else if (columna == '6') {
                            lb_E6.setIcon(bpawn_wt);
                        } else if (columna == '7') {
                            lb_E7.setIcon(bpawn_bt);
                        } else if (columna == '8') {
                            lb_E8.setIcon(bpawn_wt);
                        }
                    }
                    if (fila == 'F') {
                        if (columna == '1') {
                            lb_F1.setIcon(bpawn_wt);
                        } else if (columna == '2') {
                            lb_F2.setIcon(bpawn_bt);
                        } else if (columna == '3') {
                            lb_F3.setIcon(bpawn_wt);
                        } else if (columna == '4') {
                            lb_F4.setIcon(bpawn_bt);
                        } else if (columna == '5') {
                            lb_F5.setIcon(bpawn_wt);
                        } else if (columna == '6') {
                            lb_F6.setIcon(bpawn_bt);
                        } else if (columna == '7') {
                            lb_F7.setIcon(bpawn_wt);
                        } else if (columna == '8') {
                            lb_F8.setIcon(bpawn_bt);
                        }
                    }
                    if (fila == 'G') {
                        if (columna == '1') {
                            lb_G1.setIcon(bpawn_bt);
                        } else if (columna == '2') {
                            lb_G2.setIcon(bpawn_wt);
                        } else if (columna == '3') {
                            lb_G3.setIcon(bpawn_bt);
                        } else if (columna == '4') {
                            lb_G4.setIcon(bpawn_wt);
                        } else if (columna == '5') {
                            lb_G5.setIcon(bpawn_bt);
                        } else if (columna == '6') {
                            lb_G6.setIcon(bpawn_wt);
                        } else if (columna == '7') {
                            lb_G7.setIcon(bpawn_bt);
                        } else if (columna == '8') {
                            lb_G8.setIcon(bpawn_wt);
                        }
                    }
                    if (fila == 'H') {
                        if (columna == '1') {
                            lb_H1.setIcon(bpawn_wt);
                        } else if (columna == '2') {
                            lb_H2.setIcon(bpawn_bt);
                        } else if (columna == '3') {
                            lb_H3.setIcon(bpawn_wt);
                        } else if (columna == '4') {
                            lb_H4.setIcon(bpawn_bt);
                        } else if (columna == '5') {
                            lb_H5.setIcon(bpawn_wt);
                        } else if (columna == '6') {
                            lb_H6.setIcon(bpawn_bt);
                        } else if (columna == '7') {
                            lb_H7.setIcon(bpawn_wt);
                        } else if (columna == '8') {
                            lb_H8.setIcon(bpawn_bt);
                        }
                    }
                }
                break;
            case "REY":
                if (rb_blanco.isSelected()) {//rey blanco
                    if (fila == 'A') {
                        if (columna == '1') {
                            lb_A1.setIcon(wking_bt);
                        } else if (columna == '2') {
                            lb_A2.setIcon(wking_wt);
                        } else if (columna == '3') {
                            lb_A3.setIcon(wking_bt);
                        } else if (columna == '4') {
                            lb_A4.setIcon(wking_wt);
                        } else if (columna == '5') {
                            lb_A5.setIcon(wking_bt);
                        } else if (columna == '6') {
                            lb_A6.setIcon(wking_wt);
                        } else if (columna == '7') {
                            lb_A7.setIcon(wking_bt);
                        } else if (columna == '8') {
                            lb_A8.setIcon(wking_wt);
                        }
                    }
                    if (fila == 'B') {
                        if (columna == '1') {
                            lb_B1.setIcon(wking_wt);
                        } else if (columna == '2') {
                            lb_B2.setIcon(wking_bt);
                        } else if (columna == '3') {
                            lb_B3.setIcon(wking_wt);
                        } else if (columna == '4') {
                            lb_B4.setIcon(wking_bt);
                        } else if (columna == '5') {
                            lb_B5.setIcon(wking_wt);
                        } else if (columna == '6') {
                            lb_B6.setIcon(wking_bt);
                        } else if (columna == '7') {
                            lb_B7.setIcon(wking_wt);
                        } else if (columna == '8') {
                            lb_B8.setIcon(wking_bt);
                        }
                    }
                    if (fila == 'C') {
                        if (columna == '1') {
                            lb_C1.setIcon(wking_bt);
                        } else if (columna == '2') {
                            lb_C2.setIcon(wking_wt);
                        } else if (columna == '3') {
                            lb_C3.setIcon(wking_bt);
                        } else if (columna == '4') {
                            lb_C4.setIcon(wking_wt);
                        } else if (columna == '5') {
                            lb_C5.setIcon(wking_bt);
                        } else if (columna == '6') {
                            lb_C6.setIcon(wking_wt);
                        } else if (columna == '7') {
                            lb_C7.setIcon(wking_bt);
                        } else if (columna == '8') {
                            lb_C8.setIcon(wking_wt);
                        }
                    }
                    if (fila == 'D') {
                        if (columna == '1') {
                            lb_D1.setIcon(wking_wt);
                        } else if (columna == '2') {
                            lb_D2.setIcon(wking_bt);
                        } else if (columna == '3') {
                            lb_D3.setIcon(wking_wt);
                        } else if (columna == '4') {
                            lb_D4.setIcon(wking_bt);
                        } else if (columna == '5') {
                            lb_D5.setIcon(wking_wt);
                        } else if (columna == '6') {
                            lb_D6.setIcon(wking_bt);
                        } else if (columna == '7') {
                            lb_D7.setIcon(wking_wt);
                        } else if (columna == '8') {
                            lb_D8.setIcon(wking_bt);
                        }
                    }
                    if (fila == 'E') {
                        if (columna == '1') {
                            lb_E1.setIcon(wking_bt);
                        } else if (columna == '2') {
                            lb_E2.setIcon(wking_wt);
                        } else if (columna == '3') {
                            lb_E3.setIcon(wking_bt);
                        } else if (columna == '4') {
                            lb_E4.setIcon(wking_wt);
                        } else if (columna == '5') {
                            lb_E5.setIcon(wking_bt);
                        } else if (columna == '6') {
                            lb_E6.setIcon(wking_wt);
                        } else if (columna == '7') {
                            lb_E7.setIcon(wking_bt);
                        } else if (columna == '8') {
                            lb_E8.setIcon(wking_wt);
                        }
                    }
                    if (fila == 'F') {
                        if (columna == '1') {
                            lb_F1.setIcon(wking_wt);
                        } else if (columna == '2') {
                            lb_F2.setIcon(wking_bt);
                        } else if (columna == '3') {
                            lb_F3.setIcon(wking_wt);
                        } else if (columna == '4') {
                            lb_F4.setIcon(wking_bt);
                        } else if (columna == '5') {
                            lb_F5.setIcon(wking_wt);
                        } else if (columna == '6') {
                            lb_F6.setIcon(wking_bt);
                        } else if (columna == '7') {
                            lb_F7.setIcon(wking_wt);
                        } else if (columna == '8') {
                            lb_F8.setIcon(wking_bt);
                        }
                    }
                    if (fila == 'G') {
                        if (columna == '1') {
                            lb_G1.setIcon(wking_bt);
                        } else if (columna == '2') {
                            lb_G2.setIcon(wking_wt);
                        } else if (columna == '3') {
                            lb_G3.setIcon(wking_bt);
                        } else if (columna == '4') {
                            lb_G4.setIcon(wking_wt);
                        } else if (columna == '5') {
                            lb_G5.setIcon(wking_bt);
                        } else if (columna == '6') {
                            lb_G6.setIcon(wking_wt);
                        } else if (columna == '7') {
                            lb_G7.setIcon(wking_bt);
                        } else if (columna == '8') {
                            lb_G8.setIcon(wking_wt);
                        }
                    }
                    if (fila == 'H') {
                        if (columna == '1') {
                            lb_H1.setIcon(wking_wt);
                        } else if (columna == '2') {
                            lb_H2.setIcon(wking_bt);
                        } else if (columna == '3') {
                            lb_H3.setIcon(wking_wt);
                        } else if (columna == '4') {
                            lb_H4.setIcon(wking_bt);
                        } else if (columna == '5') {
                            lb_H5.setIcon(wking_wt);
                        } else if (columna == '6') {
                            lb_H6.setIcon(wking_bt);
                        } else if (columna == '7') {
                            lb_H7.setIcon(wking_wt);
                        } else if (columna == '8') {
                            lb_H8.setIcon(wking_bt);
                        }
                    }
                } else {//rey negro
                    if (fila == 'A') {
                        if (columna == '1') {
                            lb_A1.setIcon(bking_bt);
                        } else if (columna == '2') {
                            lb_A2.setIcon(bking_wt);
                        } else if (columna == '3') {
                            lb_A3.setIcon(bking_bt);
                        } else if (columna == '4') {
                            lb_A4.setIcon(bking_wt);
                        } else if (columna == '5') {
                            lb_A5.setIcon(bking_bt);
                        } else if (columna == '6') {
                            lb_A6.setIcon(bking_wt);
                        } else if (columna == '7') {
                            lb_A7.setIcon(bking_bt);
                        } else if (columna == '8') {
                            lb_A8.setIcon(bking_wt);
                        }
                    }
                    if (fila == 'B') {
                        if (columna == '1') {
                            lb_B1.setIcon(bking_wt);
                        } else if (columna == '2') {
                            lb_B2.setIcon(bking_bt);
                        } else if (columna == '3') {
                            lb_B3.setIcon(bking_wt);
                        } else if (columna == '4') {
                            lb_B4.setIcon(bking_bt);
                        } else if (columna == '5') {
                            lb_B5.setIcon(bking_wt);
                        } else if (columna == '6') {
                            lb_B6.setIcon(bking_bt);
                        } else if (columna == '7') {
                            lb_B7.setIcon(bking_wt);
                        } else if (columna == '8') {
                            lb_B8.setIcon(bking_bt);
                        }
                    }
                    if (fila == 'C') {
                        if (columna == '1') {
                            lb_C1.setIcon(bking_bt);
                        } else if (columna == '2') {
                            lb_C2.setIcon(bking_wt);
                        } else if (columna == '3') {
                            lb_C3.setIcon(bking_bt);
                        } else if (columna == '4') {
                            lb_C4.setIcon(bking_wt);
                        } else if (columna == '5') {
                            lb_C5.setIcon(bking_bt);
                        } else if (columna == '6') {
                            lb_C6.setIcon(bking_wt);
                        } else if (columna == '7') {
                            lb_C7.setIcon(bking_bt);
                        } else if (columna == '8') {
                            lb_C8.setIcon(bking_wt);                      
                        }
                    }
                    if (fila == 'D') {
                        if (columna == '1') {
                            lb_D1.setIcon(bking_wt);
                        } else if (columna == '2') {
                            lb_D2.setIcon(bking_bt);
                        } else if (columna == '3') {
                            lb_D3.setIcon(bking_wt);
                        } else if (columna == '4') {
                            lb_D4.setIcon(bking_bt);
                        } else if (columna == '5') {
                            lb_D5.setIcon(bking_wt);
                        } else if (columna == '6') {
                            lb_D6.setIcon(bking_bt);
                        } else if (columna == '7') {
                            lb_D7.setIcon(bking_wt);
                        } else if (columna == '8') {
                            lb_D8.setIcon(bking_bt);
                        }
                    }
                    if (fila == 'E') {
                        if (columna == '1') {
                            lb_E1.setIcon(bking_bt);
                        } else if (columna == '2') {
                            lb_E2.setIcon(bking_wt);
                        } else if (columna == '3') {
                            lb_E3.setIcon(bking_bt);
                        } else if (columna == '4') {
                            lb_E4.setIcon(bking_wt);
                        } else if (columna == '5') {
                            lb_E5.setIcon(bking_bt);
                        } else if (columna == '6') {
                            lb_E6.setIcon(bking_wt);
                        } else if (columna == '7') {
                            lb_E7.setIcon(bking_bt);
                        } else if (columna == '8') {
                            lb_E8.setIcon(bking_wt);
                        }
                    }
                    if (fila == 'F') {
                        if (columna == '1') {
                            lb_F1.setIcon(bking_wt);
                        } else if (columna == '2') {
                            lb_F2.setIcon(bking_bt);
                        } else if (columna == '3') {
                            lb_F3.setIcon(bking_wt);
                        } else if (columna == '4') {
                            lb_F4.setIcon(bking_bt);
                        } else if (columna == '5') {
                            lb_F5.setIcon(bking_wt);
                        } else if (columna == '6') {
                            lb_F6.setIcon(bking_bt);
                        } else if (columna == '7') {
                            lb_F7.setIcon(bking_wt);
                        } else if (columna == '8') {
                            lb_F8.setIcon(bking_bt);
                        }
                    }
                    if (fila == 'G') {
                        if (columna == '1') {
                            lb_G1.setIcon(bking_bt);
                        } else if (columna == '2') {
                            lb_G2.setIcon(bking_wt);
                        } else if (columna == '3') {
                            lb_G3.setIcon(bking_bt);
                        } else if (columna == '4') {
                            lb_G4.setIcon(bking_wt);
                        } else if (columna == '5') {
                            lb_G5.setIcon(bking_bt);
                        } else if (columna == '6') {
                            lb_G6.setIcon(bking_wt);
                        } else if (columna == '7') {
                            lb_G7.setIcon(bking_bt);
                        } else if (columna == '8') {
                            lb_G8.setIcon(bking_wt);
                        }
                    }
                    if (fila == 'H') {
                        if (columna == '1') {
                            lb_H1.setIcon(bking_wt);
                        } else if (columna == '2') {
                            lb_H2.setIcon(bking_bt);
                        } else if (columna == '3') {
                            lb_H3.setIcon(bking_wt);
                        } else if (columna == '4') {
                            lb_H4.setIcon(bking_bt);
                        } else if (columna == '5') {
                            lb_H5.setIcon(bking_wt);
                        } else if (columna == '6') {
                            lb_H6.setIcon(bking_bt);
                        } else if (columna == '7') {
                            lb_H7.setIcon(bking_wt);
                        } else if (columna == '8') {
                            lb_H8.setIcon(bking_bt);
                        }
                    }
                }
                break;
        }
        int x=-1, y=-1;
        switch(fila){
            case 'A': x=0;
                break;
            case 'B': x=1;
                break;
            case 'C': x=2;
                break;
            case 'D': x=3;
                break;
            case 'E': x=4;
                break;
            case 'F': x=5;
                break;
            case 'G': x=6;
                break;
            case 'H': x=7;
                break;
        }
        
        switch(columna){
            case '1': y=0;
                break;
            case '2': y=1;
                break;
            case '3': y=2;
                break;
            case '4': y=3;
                break;
            case '5': y=4;
                break;
            case '6': y=5;
                break;
            case '7': y=6;
                break;
            case '8': y=7;
                break;
        }
        String pieza="";
        if(rb_blanco.isSelected()){
            pieza=tipo+" BLANCO";
        }else{
            pieza=tipo+" NEGRO";
        }
        tablero[x][y]= new Movimiento(pieza,x,y);
        tf_posicion.setText("");
    }//GEN-LAST:event_jb_ingresarCoordenadasMouseClicked

    private void jb_nuevaPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevaPartidaMouseClicked
        llenar();
        Icon gray = new ImageIcon("src/Icons/gray_tile.png");
        Icon white = new ImageIcon("src/Icons/white_tile.png");
        lb_A1.setIcon(gray);
        lb_A2.setIcon(white);
        lb_A3.setIcon(gray);
        lb_A4.setIcon(white);
        lb_A5.setIcon(gray);
        lb_A6.setIcon(white);
        lb_A7.setIcon(gray);
        lb_A8.setIcon(white);

        lb_B1.setIcon(white);
        lb_B2.setIcon(gray);
        lb_B3.setIcon(white);
        lb_B4.setIcon(gray);
        lb_B5.setIcon(white);
        lb_B6.setIcon(gray);
        lb_B7.setIcon(white);
        lb_B8.setIcon(gray);

        lb_C1.setIcon(gray);
        lb_C2.setIcon(white);
        lb_C3.setIcon(gray);
        lb_C4.setIcon(white);
        lb_C5.setIcon(gray);
        lb_C6.setIcon(white);
        lb_C7.setIcon(gray);
        lb_C8.setIcon(white);

        lb_D1.setIcon(white);
        lb_D2.setIcon(gray);
        lb_D3.setIcon(white);
        lb_D4.setIcon(gray);
        lb_D5.setIcon(white);
        lb_D6.setIcon(gray);
        lb_D7.setIcon(white);
        lb_D8.setIcon(gray);

        lb_E1.setIcon(gray);
        lb_E2.setIcon(white);
        lb_E3.setIcon(gray);
        lb_E4.setIcon(white);
        lb_E5.setIcon(gray);
        lb_E6.setIcon(white);
        lb_E7.setIcon(gray);
        lb_E8.setIcon(white);

        lb_F1.setIcon(white);
        lb_F2.setIcon(gray);
        lb_F3.setIcon(white);
        lb_F4.setIcon(gray);
        lb_F5.setIcon(white);
        lb_F6.setIcon(gray);
        lb_F7.setIcon(white);
        lb_F8.setIcon(gray);

        lb_G1.setIcon(gray);
        lb_G2.setIcon(white);
        lb_G3.setIcon(gray);
        lb_G4.setIcon(white);
        lb_G5.setIcon(gray);
        lb_G6.setIcon(white);
        lb_G7.setIcon(gray);
        lb_G8.setIcon(white);

        lb_H1.setIcon(white);
        lb_H2.setIcon(gray);
        lb_H3.setIcon(white);
        lb_H4.setIcon(gray);
        lb_H5.setIcon(white);
        lb_H6.setIcon(gray);
        lb_H7.setIcon(white);
        lb_H8.setIcon(gray);
    }//GEN-LAST:event_jb_nuevaPartidaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (rb_peon.isSelected()) {//arbol para coronar un peon

        } else if (rb_caballo.isSelected()) {//arbol para comer un caballo

        } else if (rb_rey.isSelected()) {//arbol para poner en jaque al rey

        }
    }//GEN-LAST:event_jButton1MouseClicked

    
    public void llenar(){
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                tablero[i][j]=null;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_color;
    private javax.swing.ButtonGroup bg_jugada;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_ingresarCoordenadas;
    private javax.swing.JButton jb_nuevaPartida;
    private javax.swing.JDialog jd_movimientos;
    private javax.swing.JLabel lb_A1;
    private javax.swing.JLabel lb_A2;
    private javax.swing.JLabel lb_A3;
    private javax.swing.JLabel lb_A4;
    private javax.swing.JLabel lb_A5;
    private javax.swing.JLabel lb_A6;
    private javax.swing.JLabel lb_A7;
    private javax.swing.JLabel lb_A8;
    private javax.swing.JLabel lb_B1;
    private javax.swing.JLabel lb_B2;
    private javax.swing.JLabel lb_B3;
    private javax.swing.JLabel lb_B4;
    private javax.swing.JLabel lb_B5;
    private javax.swing.JLabel lb_B6;
    private javax.swing.JLabel lb_B7;
    private javax.swing.JLabel lb_B8;
    private javax.swing.JLabel lb_C1;
    private javax.swing.JLabel lb_C2;
    private javax.swing.JLabel lb_C3;
    private javax.swing.JLabel lb_C4;
    private javax.swing.JLabel lb_C5;
    private javax.swing.JLabel lb_C6;
    private javax.swing.JLabel lb_C7;
    private javax.swing.JLabel lb_C8;
    private javax.swing.JLabel lb_D1;
    private javax.swing.JLabel lb_D2;
    private javax.swing.JLabel lb_D3;
    private javax.swing.JLabel lb_D4;
    private javax.swing.JLabel lb_D5;
    private javax.swing.JLabel lb_D6;
    private javax.swing.JLabel lb_D7;
    private javax.swing.JLabel lb_D8;
    private javax.swing.JLabel lb_E1;
    private javax.swing.JLabel lb_E2;
    private javax.swing.JLabel lb_E3;
    private javax.swing.JLabel lb_E4;
    private javax.swing.JLabel lb_E5;
    private javax.swing.JLabel lb_E6;
    private javax.swing.JLabel lb_E7;
    private javax.swing.JLabel lb_E8;
    private javax.swing.JLabel lb_F1;
    private javax.swing.JLabel lb_F2;
    private javax.swing.JLabel lb_F3;
    private javax.swing.JLabel lb_F4;
    private javax.swing.JLabel lb_F5;
    private javax.swing.JLabel lb_F6;
    private javax.swing.JLabel lb_F7;
    private javax.swing.JLabel lb_F8;
    private javax.swing.JLabel lb_G1;
    private javax.swing.JLabel lb_G2;
    private javax.swing.JLabel lb_G3;
    private javax.swing.JLabel lb_G4;
    private javax.swing.JLabel lb_G5;
    private javax.swing.JLabel lb_G6;
    private javax.swing.JLabel lb_G7;
    private javax.swing.JLabel lb_G8;
    private javax.swing.JLabel lb_H1;
    private javax.swing.JLabel lb_H2;
    private javax.swing.JLabel lb_H3;
    private javax.swing.JLabel lb_H4;
    private javax.swing.JLabel lb_H5;
    private javax.swing.JLabel lb_H6;
    private javax.swing.JLabel lb_H7;
    private javax.swing.JLabel lb_H8;
    private javax.swing.JRadioButton rb_blanco;
    private javax.swing.JRadioButton rb_caballo;
    private javax.swing.JRadioButton rb_negro;
    private javax.swing.JRadioButton rb_peon;
    private javax.swing.JRadioButton rb_rey;
    private javax.swing.JTextField tf_posicion;
    // End of variables declaration//GEN-END:variables

    Movimiento[][] tablero= new Movimiento[8][8];
    Movimiento[][] movimientos= new Movimiento[8][8];
    //Tablero tablero = new Tablero();
    //Tablero movimientos = new Tablero();
}
